# Generated by Django 2.0.1 on 2018-01-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180119_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
